jan-api-gateway:
  replicaCount: 1
  image:
    repository: jan-api-gateway
    tag: latest
  service:
    type: ClusterIP
    port: 8080
  env:
    - name: JAN_INFERENCE_MODEL_URL
      value: http://jan-server-jan-inference-model:8101
    - name: SERPER_API_KEY
      value: your_key_from_serper_api
    - name: JWT_SECRET
      value: 41/YJHCG4kP5uln/YGK5pFHAzY3skF+6yYWDiYqc8WuoOcw51VV0aUhNo3Ueva572ASWmkxpkF+B5gPBLMOPzQ==
    - name: OAUTH2_GOOGLE_CLIENT_ID
      value: your_oauth2_google_client_id
    - name: OAUTH2_GOOGLE_CLIENT_SECRET
      value: your_oauth2_google_client_secret
    - name: OAUTH2_GOOGLE_REDIRECT_URL
      value: your_oauth2_google_redirect_url
    - name: DB_POSTGRESQL_WRITE_DSN
      value: host=jan-server-postgresql user=jan-user password=jan-password dbname=jan port=5432 sslmode=disable
    - name: DB_POSTGRESQL_READ1_DSN
      value: host=jan-server-postgresql user=jan-user password=jan-password dbname=jan port=5432 sslmode=disable
    - name: APIKEY_SECRET
      value: fhWMCXu29gKRcs6//I0HwaQgvTgv0uMdLRshU5cyC+4=
    - name: ALLOWED_CORS_HOSTS
      value: http://localhost:8080
    - name: REDIS_URL
      value: redis://jan-server-redis-master:6379
    - name: REDIS_PASSWORD
      value: ""
    - name: REDIS_DB
      value: "0"

jan-inference-model:
  replicaCount: 1
  image:
    repository: jan-inference-model
    tag: latest
  service:
    type: ClusterIP
    port: 8101

postgresql:
  auth:
    database: jan
    username: jan-user
    password: jan-password

redis:
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  replica:
    replicaCount: 1
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"